spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/e_commerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update